### ISSUE TITLE
Enter valid email

### ISSUE THREAD

**Issue by Hax4us** [roccomuso/no-ip#1]
My username is correct but why error is coming

**Comment by roccomuso** [comment]
@Hax4us which error?
Paste something, give us more information.

**Comment by Hax4us** [comment]
no-ip -h lokeshh.ddns.net -u lokeshhh -p my password

/data/data/com.termux/files/usr/lib/node_modules/no-ip/lib/no-ip.js:14
  if (!validator.isEmail(opts.user)) throw Error('Provide a valid Email')
                                     ^

Error: Provide a valid Email
    at new NoIP (/data/data/com.termux/files/usr/lib/node_modules/no-ip/lib/no-ip.js:14:44)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/no-ip/bin/cli.js:6:12)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3

**Comment by roccomuso** [comment]
The error clearly says to provide the email as username, not the username itself.

> No-IP uses an email address as the username.

**Comment by Hax4us** [comment]
Thnx bro... :D

**Comment by roccomuso** [comment]
@Hax4us You're welcome, feel free to star the project ;)
Btw I have also a [termux](/roccomuso/termux) package, check it out.

**Comment by Hax4us** [comment]
Awsmm...your all repo 👌👌
